# frozen_string_literal: true
source "https://rubygems.org"

# gem "rails"
gem 'data_mapper'
gem 'dm-sqlite-adapter'
gem 'dm-migrations'
gem 'dm-constraints'
gem 'sinatra'
gem "sinatra-cross_origin", "~> 0.3.1"
gem 'hashie'
gem 'json'
gem 'sqlite3'
